In [1]:
import numpy as np
np.__version__

'1.21.2'

In [2]:
np.array([1,2,"1"])

array(['1', '2', '1'], dtype='<U21')

In [4]:
classic_list = [1,2,3,5,7,11]
type(classic_list)

list

In [5]:
numpy_array = np.array(classic_list)
type(numpy_array)

numpy.ndarray

In [6]:
numpy_array.shape

(6,)

In [7]:
np.array([2,4]).mean()

3.0

In [9]:
numpy_matrix = np.array([[1,2,3], [5,7,11]])
numpy_matrix.shape

(2, 3)

In [10]:
matrix1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
matrix1[0, :]

array([1, 2, 3])

In [11]:
matrix1[:,-1]

array([3, 6, 9])

In [12]:
matrix1[:, 1]

array([2, 5, 8])

In [13]:
matrix2 = np.array([
    [1,2,3],
    [0,8,10],
    [1,10,12]
])

In [14]:
matrix2.sum()

47

In [15]:
matrix1[:,0]

array([1, 4, 7])

matrix2.sum(axis=0)

In [17]:
matrix2.sum(axis=1)

array([ 6, 18, 23])

In [18]:
np.array([1,2]) + np.array([8,9])

array([ 9, 11])

In [44]:
np.array([
    [1,2],
    [3,4]
]) +\
np.array([
    [8,9],
    [10,11]
])

array([[ 9, 11],
       [13, 15]])

"+\" ten symbol oznacza, że dodaje kolejne wiersze do siebie

In [77]:
np.array([
    [1,2],
    [3,4]
]).dot([1,1])

array([3, 7])

In [193]:
for counts in range(11,1,-1):
    vector = list(range(counts))
    break

In [194]:
vector.remove(0)
print(vector)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [195]:
vector2 = [1]*10

In [196]:
print(vector2)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [198]:
np.array(vector)+ np.array(vector2)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [202]:
for counts in range(26,1,-1):
    matrix4 = list(range(counts))
    break

matrix4.remove(0)
print(matrix4)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


In [230]:
matrix5 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

matrix5.mean(axis=1)

array([ 3.,  8., 13., 18., 23.])

In [219]:
matrix6 = np.matrix(np.arange(1,26).reshape((5,5)))

In [220]:
matrix6

matrix([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])

In [224]:
vector7 = np.array(np.arange(1,11))
vector7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [231]:
matrix6.mean(0)

matrix([[11., 12., 13., 14., 15.]])

In [232]:
matrix6.mean(1)

matrix([[ 3.],
        [ 8.],
        [13.],
        [18.],
        [23.]])